import json
from pathlib import Path
from typing import Literal

from pydantic import BaseModel


class Block(BaseModel):
    id: int
    page: int
    type: Literal["heading", "paragraph", "verse", "code", "image", "page_break"]
    level: int | None = None
    text: str
    # Pre-rendered inline markup (bold/italic/line breaks/embedded image) for the
    # original-language side only — safe HTML generated by our own extraction code.
    html: str | None = None
    # Rough-pass output, kept separate from the final polished text so the two
    # translation phases can run as separate whole-book passes (one model loaded
    # at a time) instead of alternating models every chunk.
    rough_text: str | None = None
    translated_text: str | None = None
    translation_error: bool = False
    order_key: int


class BookStructure(BaseModel):
    book_id: str
    source_lang: str
    page_count: int
    blocks: list[Block]

    def save(self, path: Path) -> None:
        path.write_text(self.model_dump_json(indent=1), encoding="utf-8")

    @classmethod
    def load(cls, path: Path) -> "BookStructure":
        return cls.model_validate(json.loads(path.read_text(encoding="utf-8")))
